### ISSUE TITLE
Unfinished top-level await exit code is ignored

### ISSUE THREAD

**Issue by Drarig29** [jakebailey/pprof-it#1]
Hi! I found a bug while profiling a stream that was paused. I thought "Yeah! I fixed my memory leak! 🎉 " when looking at the generated profile.

But in fact, there was no memory leak _because Node.js was exiting with code `13`_ 😅 

**Minimal reproducible example:**
- Create a `example.mjs` file with a promise that will never resolve:
  ```js
  await new Promise(() => {})
  ```
- `node example.mjs` will have an exit code of `13` (cf. [exit codes](https://nodejs.org/api/process.html#exit-codes))
- but `npx pprof-it example.mjs` has an exit code of `0`

FYI, I first tried to reproduce with a simple `npx pprof-it -e 'process.exit(13)'` but it worked.

**Comment by jakebailey** [comment]
That's really strange. I don't do anything with the exit code besides exit on an error in this package itself.

Can you try with `PPROF_SIGNAL_EXIT=off`?

**Comment by Drarig29** [comment]
It worked with `PPROF_SIGNAL_EXIT=off`, thanks!

Should this be the default? I would rather not have to always remember about setting this environment variable.

**Comment by jakebailey** [comment]
No, it shouldn't be the default, otherwise you won't get a profile if you exit the process early via Ctrl+C or similar. This must be a bug in [`signal-exit`](https://www.npmjs.com/package/signal-exit).

**Comment by jakebailey** [comment]
I've found a workaround; the fix is now available in v1.2.1.

**Comment by Drarig29** [comment]
Thanks a lot, this tool is very helpful! I finally fixed my memory leak! 🥳

**Comment by jakebailey** [comment]
Nice!

Though, I think Chrome/Edge's memory profiler actually has a nice new leak-finding mode which may work better these days.
